### Instituto Superior Tecnologico Quito

![jupyter](img/itq.png)

**Nombre:** Alan Velasco, Maiccol Zurita, Christopher Rodriguez


**Fecha:** 26/02/20236

# Normalización de datos con MinMaxScaler
Ejemplo práctico usando sklearn.

In [2]:
from sklearn import preprocessing
import numpy as np

In [3]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [4]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [5]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [6]:
# Verificación: fit + transform por separado
X_train_2 = np.copy(X_train)

f = normalizer.fit(X_train)
X_train_norm_2 = f.transform(X_train_2)

print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [7]:
# Normalizar un nuevo conjunto de datos de test
X_test = np.array([[ 1., -3.,  2.],
                   [ 3.,  0.,  0.],
                   [ 0.,  4., -1.]])

# IMPORTANTE: solo transform (no fit)
X_test_norm = normalizer.transform(X_test)

print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


In [8]:
# Normalizar un nuevo conjunto de datos de test
X_test = np.array([[ 1., -3.,  2.],
                   [ 3.,  0.,  0.],
                   [ 0.,  4., -1.]])

# IMPORTANTE: solo transform (no fit)
X_test_norm = normalizer.transform(X_test)

print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]
