### Instituto Superior Tecnologico Quito

![jupyter](img/itq.png)

**Nombre:** Alan Velasco, Maiccol Zurita, Christopher Rodriguez


**Fecha:** 26/02/20236

In [1]:
from sklearn import preprocessing
import numpy as np

In [10]:
# Carga de datos.
X_train = np.array([[ 1., -4.,  5.],
                    [ 5.,  0.,  2.],
                    [ 0.,  6., -3.]])

print(X_train)

[[ 1. -4.  5.]
 [ 5.  0.  2.]
 [ 0.  6. -3.]]


In [11]:
# Limpieza de datos: normalización.
normalizer = preprocessing.MinMaxScaler()
X_train_norm = normalizer.fit_transform(X_train)

In [12]:
# Salida de resultados.
print(X_train_norm)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [13]:
# Ejemplo para ver que los resultados son iguales si aplicamos los métodos "fit" y "transform" por separado
X_train_2 = np.copy(X_train)
f = normalizer.fit(X_train)
X_train_norm_2 = f.transform(X_train_2)
print(X_train_norm_2)

[[0.2   0.    1.   ]
 [1.    0.4   0.625]
 [0.    1.    0.   ]]


In [14]:
# Comprobar si las matrices normalizadas son iguales
print(np.array_equiv(X_train_norm, X_train_norm_2))

True


In [20]:
# Normalizar un nuevo conjunto de datos de test (SOLO HAY QUE APLICAR EL MÉTODO "transform", NO EL "fit")
X_test = np.array([[ 1., -3.,  2.],
                    [ 3.,  0.,  0.],
                    [ 0.,  4., -1.]])
# Normalizar los datos 
X_test_norm = f.transform(X_test)
print(X_test_norm)

[[0.2   0.1   0.625]
 [0.6   0.4   0.375]
 [0.    0.8   0.25 ]]


### Ejemplo difernte

In [17]:
# Nuevos datos
X_train = np.array([[10., 200.,  3.],
                    [20., 100.,  6.],
                    [15., 300.,  9.]])

print("Datos originales:")
print(X_train)


Datos originales:
[[ 10. 200.   3.]
 [ 20. 100.   6.]
 [ 15. 300.   9.]]


In [18]:
# Crear normalizador
scaler = preprocessing.MinMaxScaler()

# Ajustar y transformar
X_train_norm = scaler.fit_transform(X_train)

print("\nDatos normalizados (train):")
print(X_train_norm)


Datos normalizados (train):
[[0.  0.5 0. ]
 [1.  0.  0.5]
 [0.5 1.  1. ]]


In [19]:
X_test = np.array([[12., 150.,  4.],
                   [18., 250.,  8.]])

# SOLO transform 
X_test_norm = scaler.transform(X_test)

print("\nDatos normalizados (test):")
print(X_test_norm)


Datos normalizados (test):
[[0.2        0.25       0.16666667]
 [0.8        0.75       0.83333333]]
